root: true

env:
  browser: true
  es6: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - google
  - prettier

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: false
    globalReturn: false

plugins:
  - import
  - prettier

rules:
  import/order: error
  import/unambiguous: error
  no-restricted-syntax:
    - error
    - BindExpression
    - Decorator
    - DoExpression
    - ExportDefaultSpecifier
    - ExportNamespaceSpecifier
    - TypeAnnotation
    - JSXElement
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5

settings:
  import/extensions: ['.mjs', '.js']
  import/parsers:
    babel-eslint: ['.js']
    espree: ['.mjs']
