language: node_js
node_js:
  - "node"

# Travis is pretty behind the curve on their Yarn support...
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Using-a-specific-yarn-version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
