parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
